### ISSUE TITLE
issue with php v7.2  

### ISSUE THREAD

**Issue by MoGnedy** [alterphp/EasyAdminExtensionBundle#124]
Warning: count(): Parameter must be an array or an object that implements Countable

ErrorException
in vendor/alterphp/easyadmin-extension-bundle/src/EventListener/PostQueryBuilderSubscriber.php (line 172)
                    ->setParameter($parameter, $value)                ; 
               break;  
         
 case ListFilter::OPERATOR_IN:              
               if (0 < \count($value)) {      
              $queryBuilder            
            ->andWhere(\sprintf('%s %s (:%s)', $queryField, 'IN', $parameter))                        ->setParameter($parameter, $value)                    ;         
       }

**Comment by alterphp** [comment]
Hi @MoGnedy !

Sorry for late response, I've been on holidays for a week... I think your problem is that default filter guesser tries to define a value-list slector (ChoiceType) for string fields. In your case, you should configure `like` operator.

Did you change anything to the filters form rendering to get this error ?

**Comment by MoGnedy** [comment]
No I didn’t change anything. 
 And if i change php version to 7.1 everything works fine.

**Comment by alterphp** [comment]
Can I see your entity and easy_admin config ? What is the value of `$value` when exception is thrown ?

**Comment by alterphp** [comment]
No feedback, closing
