### ISSUE TITLE
Access denied when the user does not have access to the first entity in EasyAdmin config

### ISSUE THREAD

**Issue by soefelix** [alterphp/EasyAdminExtensionBundle#135]
Hi, I have a question 

In the original bundle there is the function **redirectToBackendHomepage()** in the controller which redirects to the first configured entity.
When using roles, It's possible to fall in the case that the logged user does not have access to this first entity (when accessing with **/admin/**). In that case there is a 403 error page.

Where do you think the check should be done?
We did it by overriding **redirectToBackendHomepage()** but I'm not sure if it's accurate.

Another solution may be to have a default landing page which only requires the role ROLE_USER but sometimes it's not necessary.

WDYT?

Thanks for this bundle

**Comment by soefelix** [comment]
Here is what we did

```
public function redirectToBackendHomepage()
{
    $entity = $this->config['homepage']['params']['entity'];
    $role   = $this->config['entities'][$entity]['role'];
    $homepageConfig = $this->config['homepage'];

    if (!$this->isGranted($role)) {
        foreach ($this->config['entities'] as $entity) {
            if ($this->isGranted($entity['role'])) {
               $homepageConfig['params']['entity'] = $entity['name'];
           }
        }
   }
        
    $url = isset($homepageConfig['url'])
        ? $homepageConfig['url']
        : $this->get('router')->generate($homepageConfig['route'], $homepageConfig['params']);

    return $this->redirect($url);
}
```

**Comment by alterphp** [comment]
Hi @soefelix !

As you spotted default homepage may have side effects with role based security.

The first entity is the most unpredictable way, and that's why redefining `redirectToBackendHomepage` method is the best workaround.

But you can also define the default homepage by setting the `default` option in the menu config (see https://symfony.com/doc/current/bundles/EasyAdminBundle/book/menu-configuration.html#changing-the-backend-index-page). This may help you if the default menu entry is not restricted to a particular role => this is what I use.

**Comment by soefelix** [comment]
Hi @alterphp,

Thanks for the fast reply.
We'll choose the best option depending on each project uses cases
