### ISSUE TITLE
When adding new items to collection , the autocomplete field bug

### ISSUE THREAD

**Issue by lucas-cld** [alterphp/EasyAdminExtensionBundle#172]
When adding new items to collection in a form which using autocomplete_easyadmin with attr : create : true, the new and the old autocomplete_easyadmin don't propose the creation modal aymore when we don't find on object in autocomplete field.

Can you help me to solve this issue please

**Comment by alterphp** [comment]
Hi @lucas-cld !

I do not personally use this feature. It has been provided by @gonzakpo. Do you have any log in the JS console ?

**Comment by lucas-cld** [comment]
No , it's for that it's weird, i don't have any error

**Comment by lucas-cld** [comment]
After searching i find a way to get off the bug , i just add this function in the 'autocomplete-create.js'. 

`$('#main').on('easyadmin.collection.item-added', '[data-prototype]', function () {
  $(document).ready(function(){
    createAutoCompleteCreateFields()
  })
});`

Don't know if it's the best way, but it works

**Comment by alterphp** [comment]
Hello @lucas-cld ! Is the autocomplete contained in the added collection item ?

**Comment by lucas-cld** [comment]
Hey @alterphp, yes it's that

**Comment by alterphp** [comment]
Sorry for late answer, I missed this one.

This issue is a javascript behavior => a new input is added to the DOM, and it requires some JS initialization. For now I prefer not initializing every JS fields on the `easyadmin.collection.item-added` event in the bundle. Events may change in the future.

Your solution is good, and you can add this code only where you need it, as you want.
