### ISSUE TITLE
Easy Admin 3.2 supported?

### ISSUE THREAD

**Issue by excitedbox** [alterphp/EasyAdminExtensionBundle#196]
I just tried to install this extension and got a message saying that easyAdmin 3.2 is not supported. Is this coming or should I downgrade to 3.1? Or do I just need to update the project file to let the dependency resolve?

Ideally I need this extension tomorrow for a demo, so I may just downgrade in the meantime since it is only a minor update since 3.1

**Comment by Pierstoval** [comment]
I'm not even sure that this bundle would support EasyAdmin 3 at all, since v3 introduced a ginormous amount of BC breaks in its internal structure.

**Comment by alterphp** [comment]
This extension bundle goal is to fill the gap for some missing features I wanted to have with EasyAdmin 2. EasyAdmin 3 is nearly a whole new codebase. Some of those missing features are now directly implemented in EasyAdmin : list filters, permissions. Maybe not the embedded lists but is was on their projects list some time ago.

That's why I don't plan to migrate this bundle to EasyAdmin 3.
